# models/schema.yml

version: 2

models:
  - name: stock_data
    description: "Raw stock data pulled from the STOCK.data.market_dat table."
    columns:
      - name: date
        description: "Date of the stock data."
        tests:
          - not_null
      - name: symbol
        description: "Stock symbol (e.g., AAPL for Apple, TSLA for Tesla)."
        tests:
          - not_null
      - name: open
        description: "Opening price of the stock on the given date."
        tests:
          - not_null
      - name: high
        description: "Highest price of the stock on the given date."
      - name: low
        description: "Lowest price of the stock on the given date."
      - name: close
        description: "Closing price of the stock on the given date."
      - name: volume
        description: "Trading volume of the stock on the given date."

  - name: stock_analysis
    description: "Table containing stock analysis metrics such as moving averages and RSI."
    columns:
      - name: date
        description: "Date of the analysis data."
        tests:
          - not_null
      - name: symbol
        description: "Stock symbol (e.g., AAPL, TSLA)."
        tests:
          - not_null
      - name: close
        description: "Closing price of the stock on the given date."
      - name: moving_avg_7d
        description: "7-day moving average of the stock's closing price."
      - name: rsi_14d
        description: "14-day Relative Strength Index of the stock's closing price."