# models/source.yml

version: 2

sources:
  - name: stock_data_source
    description: "Source data for stock information loaded from Snowflake."
    schema: "data"
    database: "STOCK"
    tables:
      - name: market_dat
        description: "Raw stock data table containing information for multiple symbols."
        columns:
          - name: date
            description: "Date of the stock data."
            tests:
              - not_null
          - name: symbol
            description: "Stock symbol (e.g., AAPL, TSLA)."
            tests:
              - not_null
          - name: open
            description: "Opening price of the stock on the given date."
          - name: high
            description: "Highest price of the stock on the given date."
          - name: low
            description: "Lowest price of the stock on the given date."
          - name: close
            description: "Closing price of the stock on the given date."
          - name: volume
            description: "Trading volume of the stock on the given date."