dwlab2:
  outputs:
    dev:
      account: DXVFTZY-CDB70790
      database: dev
      password: ***********
      role: ACCOUNTADMIN
      schema: analytics
      threads: 1
      type: snowflake
      user: deekshachauhan7
      warehouse: COMPUTE_WH
  target: dev
